/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author anapl
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLoginAdministrador = new javax.swing.JButton();
        bLoginPropietario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLoginAdministrador.setText("Login Administrador");
        bLoginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginAdministradorActionPerformed(evt);
            }
        });

        bLoginPropietario.setText("Login Propietario");
        bLoginPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginPropietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(bLoginAdministrador)
                .addGap(67, 67, 67)
                .addComponent(bLoginPropietario)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLoginAdministrador)
                    .addComponent(bLoginPropietario))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginAdministradorActionPerformed
        this.loginAdministrador();        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginAdministradorActionPerformed

    private void bLoginPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginPropietarioActionPerformed
        this.loginPropietario();        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginPropietarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLoginAdministrador;
    private javax.swing.JButton bLoginPropietario;
    // End of variables declaration//GEN-END:variables

    private void loginAdministrador() {
        new DialogoLoginAdministrador(this, false).setVisible(true);
    }

    private void loginPropietario() {
        new DialogoLoginPropietario(this, false).setVisible(true);
    }

}
